APK.WEB/AlertCity-Web/AlertCity-Web/AlertCity/Controllers/EventoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AlertCity.Models;
using AlertCity.Model;
using AlertCity.Model.Repositories;

namespace AlertCity.Controllers
{
    public class EventoController : Controller, IDisposable
    {
        RepositoryEvento _Repository;
        // GET: EventoM
        public EventoController()
        {
            _Repository = new RepositoryEvento();
        }
        //lista de todos cadastrados

        private List<EventoM> Eventos()
        {
            var Lista = _Repository.SelecionarTodos();
            List<EventoM> oRetorno = new List<EventoM>();
            foreach (var obj in Lista)
            {
                EventoM oEve = new EventoM();
                oEve.Bairrof = obj.Bairrof;
                oEve.Cepf = obj.Cepf;
                oEve.Cidadef = obj.Cidadef;
                oEve.Dataf = obj.Dataf;
                oEve.DescricaoEvento = obj.DescricaoEvento;
                oEve.Localizacaof = obj.Localizacaof;
                oEve.RegistroEvento = obj.RegistroEvento;
                oEve.Ruaf = obj.Ruaf;
                oEve.Telefone = obj.Telefone;
                oEve.TipoF = obj.TipoF;
                oEve.Uff = obj.Uff;
                oEve.Valorf = obj.Valorf;

                oRetorno.Add(oEve);
            }
            return oRetorno;
        }
        public ActionResult EIndex()
        {
            EventoM oEvento = new EventoM();
            oEvento.TodosEventos = Eventos();
            oEvento.Incluir = true;
            return View("EIndex", oEvento);

        }
        //=========================================================================//

        // -------- Salvar começo ---------------------//

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Salvar(EventoM oEvento)
        {
            Evento oEve = new Evento();
            oEve.Bairrof = oEvento.Bairrof;
            oEve.Cepf = oEvento.Cepf ;
            oEve.Cidadef = oEvento.Cidadef;
            oEve.Dataf = oEvento.Dataf;
            oEve.DescricaoEvento = oEvento.DescricaoEvento;
            oEve.Localizacaof = oEvento.Localizacaof;
            oEve.RegistroEvento = oEvento.RegistroEvento;
            oEve.Ruaf = oEvento.Ruaf;
            oEve.Telefone = oEvento.Telefone;
            oEve.TipoF = oEvento.TipoF;
            oEve.Uff = oEvento.Uff;
            oEve.Valorf = oEvento.Valorf;

            if (ModelState.IsValid)
            {
                try
                {
                    _Repository.Incluir(oEve);

                    ModelState.Clear();
                }
                catch (Exception ex)
                {
                    ViewBag.Alerta = "Ocorreu um erro na inclusão dos dados:" + ex.Message;
                }
                if (oEvento.Incluir == false)
                {
                    _Repository.Alterar(oEve);
                }
                ModelState.Clear();

                if (oEvento.Incluir)
                {
                    _Repository.Incluir(oEve);
                }

                else
                {
                    _Repository.Alterar(oEve);
                }

            }
            oEvento.Incluir = false;
            ModelState.Clear();
            return EIndex();
        }
        //=================================================================//
        //----------------Alterar---------------------//
        public ActionResult Alterar(int ProEvento)
        {

            //var Lista = _Repository.SelecionarTodos();
            //List<EventoM> oRetorno = new List<EventoM>();

            Evento oEve = _Repository.Selecionar(ProEvento);
            EventoM oEvento = new EventoM();
            oEvento.Bairrof = oEve.Bairrof;
            oEvento.Cepf = oEve.Cepf;
            oEvento.Cidadef = oEve.Cidadef;
            oEvento.Dataf = oEve.Dataf;
            oEvento.DescricaoEvento = oEve.DescricaoEvento;
            oEvento.Localizacaof = oEve.Localizacaof;
            oEvento.RegistroEvento = oEve.RegistroEvento;
            oEvento.Ruaf = oEve.Ruaf;
            oEvento.Telefone = oEve.Telefone;
            oEvento.TipoF = oEve.TipoF;
            oEvento.Uff = oEve.Uff;
            oEvento.Valorf = oEve.Valorf;

            oEvento.Incluir = false;
            return View("EIndex", oEvento);
        }
        //===================================================================//
        //------------------Excluir-----------------------//
        public ActionResult Excluir(int ProEvento)
        {

            Evento oEvento = _Repository.Selecionar(ProEvento);
            _Repository.Excluir(oEvento);

            return EIndex();

        }
        public new void Dispose()
        {
            _Repository.Dispose();
        }
    }
}

APK.WEB/AlertCity-Web/AlertCity-Web/AlertCity/Controllers/PrincipalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AlertCity.Controllers
{
    public class PrincipalController : Controller
    {
        public ActionResult PIndex()
        {
            return View();
        }
    }
}

APK.WEB/AlertCity-Web/AlertCity-Web/AlertCity/Views/Evento/Detalhes.cshtml
@model IEnumerable<AlertCity.Model.Evento>

<table class="table table-responsive table-hover table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TipoF)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Localizacaof)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dataf)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ruaf)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bairrof)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cidadef)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Uff)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cepf)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Valorf)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DescricaoEvento)
        </th>

        <th>Alterar</th>
        <th>Excluir</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TipoF)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Localizacaof)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dataf)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ruaf)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bairrof)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cidadef)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Uff)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cepf)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Valorf)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DescricaoEvento)
        </td>

        <td>
            <a class="btn btn-success" href="@Url.Action("Alterar",new { ProEvento=item.RegistroEvento})">Alterar</a>
        </td>
        <td>
            <a class="btn btn-danger" href="@Url.Action("Excluir",new { ProEvento=item.RegistroEvento})">Excluir</a>
        </td>
    </tr>
}

</table>

APK.WEB/AlertCity-Web/AlertCity-Web/AlertCity/Views/Evento/EIndex.cshtml
@model AlertCity.Models.EventoM

<body background="~/Imagem/Fundo.jpg" style="animation-delay:initial;">

    @using (Html.BeginForm("Salvar", "Evento", FormMethod.Post, new { @class = "form-horizontal", @role = "form", @enctype = "multipart/form-data", @id = "FrmEvento" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="Container">
                <h1>Cadastro de Eventos</h1>
                <hr />
                <div class="col-md-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.TipoF, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.TipoF, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TipoF, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Localizacaof, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Localizacaof, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Localizacaof, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Dataf, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Dataf, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Dataf, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Ruaf, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Ruaf, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Ruaf, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Bairrof, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Bairrof, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Bairrof, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Cidadef, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Cidadef, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Cidadef, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Uff, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Uff, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Uff, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Cepf, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Cepf, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Cepf, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Valorf, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Valorf, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Valorf, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DescricaoEvento, htmlAttributes: new { @class = "control-label" })
                        <div class="md-2">
                            @Html.TextArea("DescricaoEvento", null, new { htmlAttributes = new { @class = "form-control" }, rows = "8", cols = "150" })
                            @Html.ValidationMessageFor(model => model.DescricaoEvento, "", new { @class = "text-danger" })
                            <br />
                            <br />
                            <input type="submit" value="Salvar" class="btn btn-default" />
                            <br />
                            <br />
                            @Html.ActionLink("Voltar ao Entre Laços", "PIndex", "Principal")
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

    <div class="table">
        @{ Html.RenderPartial("Detalhes", @Model.SelecionarEventos());}
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</body>