APK.WEB/AlertCity-Web/AlertCity-Web/AlertCity/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using AlertCity.Model;
using AlertCity.Model.Repositories;

namespace AlertCity.Models
{
    [MetadataType(typeof(MD_Usuario))]
    public class Usuario: appCadastroUsuario
    {
        public bool Incluir { get; set; }
        public List<Usuario> TodosUsuarios { get; set; }

        internal class MD_Usuario
        {
            public int appLogin { get; set; }

            [DisplayName("Nome")]
            [Required(ErrorMessage = "Preencher  campo Nome")]
            public string appNome { get; set; }

            [DisplayName("Senha   ")]
            [Required(ErrorMessage = "Informe a senha do usuário", AllowEmptyStrings = false)]
            public string appSenha { get; set; }

            [DisplayName("Confirmar")]
            [Required(ErrorMessage = "Preencher campo Confirmar Senha")]
            public string appConfirmar { get; set; }

            [DisplayName("EMail        ")]
            [Required(ErrorMessage = "Informe a senha do usuário", AllowEmptyStrings = false)]
            public string appEmail { get; set; }

            [DisplayName("Celular  ")]
            [Required(ErrorMessage = "Preencher campo Celular")]
            public string appCelular { get; set; }

            public object Incluir { get; set; }
        }
        public List<appCadastroUsuario> SelecionarUsuarios()
        {
            RepositoryUsuario _Repository = new RepositoryUsuario();
            var Retorno = _Repository.SelecionarTodos();
            return Retorno;
        }
    }

}

APK.WEB/AlertCity-Web/AlertCity-Web/AlertCity/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AlertCity.Models;
using AlertCity.Model;
using AlertCity.Model.Repositories;
using System.ComponentModel.DataAnnotations;

namespace AlertCity.Controllers
{
    public class LoginController : Controller
    {
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult LIndex()
        {
            Session["Nome"] = null;
            return View();
          
            //return View();
        }
        public ActionResult Acessar(Usuario u)
        {
            if (ModelState.IsValid) //verifica se é válido
            {
                using (alextheodoroEntities dc = new alextheodoroEntities())
                {
                    var v = dc.appCadastroUsuario.Where(a => a.appEmail.Equals(u.appEmail) && a.appSenha.Equals(u.appSenha)).FirstOrDefault();
                    if (v != null)
                    {
                        Session["Nome"] = v.appNome.ToString();
                        return RedirectToAction("PIndex");
                    }
                }
            }
            return View("PIndex");
        }
    }
}

APK.WEB/AlertCity-Web/AlertCity-Web/AlertCity/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AlertCity.Models;
using AlertCity.Model;
using AlertCity.Model.Repositories;

namespace AlertCity.Controllers
{

    public class UsuarioController : Controller, IDisposable
    {
        RepositoryUsuario _Repository;
        // GET: Usuario
        public UsuarioController()
        {
            _Repository = new RepositoryUsuario();
        }
        //lista de todos cadastrados

        private List<Usuario> Usuarios()
        {
            var Lista = _Repository.SelecionarTodos();
            List<Usuario> oRetorno = new List<Usuario>();
            foreach (var obj in Lista)
            {
                Usuario oUsu = new Usuario();
                oUsu.appLogin = obj.appLogin;
                oUsu.appNome = obj.appNome;
                oUsu.appSenha = obj.appSenha;
                oUsu.appConfirmar = obj.appConfirmar;
                oUsu.appEmail = obj.appEmail;
                oUsu.appCelular = obj.appCelular;


                oRetorno.Add(oUsu);
            }
            return oRetorno;
        }
        public ActionResult Index()
        {
            Usuario oUsuario = new Usuario();
            oUsuario.TodosUsuarios = Usuarios();
            oUsuario.Incluir = true;
            return View("Index", oUsuario);

        }
        //=========================================================================//

        // -------- Salvar começo ---------------------//

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Salvar(Usuario oUsuario)
        {
            appCadastroUsuario oUsu = new appCadastroUsuario();
            oUsu.appLogin = oUsuario.appLogin;
            oUsu.appNome = oUsuario.appNome;
            oUsu.appSenha = oUsuario.appSenha;
            oUsu.appConfirmar = oUsuario.appConfirmar;
            oUsu.appEmail = oUsuario.appEmail;
            oUsu.appCelular = oUsuario.appCelular;
            if (ModelState.IsValid)
            {
                try
                {
                    _Repository.Incluir(oUsu);

                    ModelState.Clear();
                }
                catch (Exception ex)
                {
                    ViewBag.Alerta = "Ocorreu um erro na inclusão dos dados:" + ex.Message;
                }
                if (oUsuario.Incluir == false)
                {
                    _Repository.Alterar(oUsu);
                }
                ModelState.Clear();
                if (oUsuario.Incluir)
                {
                    _Repository.Incluir(oUsu);
                }

                else
                {
                    _Repository.Alterar(oUsu);
                }

            }
            oUsuario.Incluir = false;
            ViewBag.Mensagem = "Usuário Cadastrado";
            ModelState.Clear();
            return Index();
        }
        //=================================================================//
        //----------------Alterar---------------------//
        public ActionResult Alterar(int ProUsuario)
        {

            //var Lista = _Repository.SelecionarTodos();
            //List<Usuario> oRetorno = new List<Usuario>();

            appCadastroUsuario oUsu = _Repository.Selecionar(ProUsuario);
            Usuario oUsuario = new Usuario();
            oUsuario.appLogin = oUsu.appLogin;
            oUsuario.appNome = oUsu.appNome;
            oUsuario.appSenha = oUsu.appSenha;
            oUsuario.appConfirmar = oUsu.appConfirmar;
            oUsuario.appEmail = oUsu.appEmail;
            oUsuario.appCelular = oUsu.appCelular;

            oUsuario.Incluir = false;
            return View("Index", oUsuario);
        }
        //===================================================================//
        //------------------Excluir-----------------------//
        public ActionResult Excluir(int ProUsuario)
        {

            appCadastroUsuario oUsuario = _Repository.Selecionar(ProUsuario);
            _Repository.Excluir(oUsuario);

            return Index();

        }
        public new void Dispose()
        {
            _Repository.Dispose();
        }
    }
}

APK.WEB/AlertCity-Web/AlertCity-Web/AlertCity/Views/Usuario/Detalhes.cshtml
@model IEnumerable<AlertCity.Model.appCadastroUsuario>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.appNome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.appSenha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.appConfirmar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.appEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.appCelular)
        </th>
        <th>Alterar</th>
        <th>Excluir</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.appNome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.appSenha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.appConfirmar)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.appEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.appCelular)
        </td>
        <td>
            <a class="btn btn-success" href="@Url.Action("Alterar",new { ProUsuario=item.appLogin})">Alterar</a>
        </td>
        <td>
            <a class="btn btn-danger" href="@Url.Action("Excluir",new { ProUsuario=item.appLogin})">Excluir</a>
        </td>
    </tr>
}

</table>

APK.WEB/AlertCity-Web/AlertCity-Web/AlertCity/Views/Usuario/Index.cshtml
@model AlertCity.Models.Usuario

@if(ViewBag.Mensagem==null)
{
    ViewBag.Mensagem = "";
}

<body background="~/Imagem/Fundo.jpg" style="animation-delay:initial;">

    @using (Html.BeginForm("Salvar", "Usuario", FormMethod.Post, new { @class = "form-horizontal", @role = "form", @enctype = "multipart/form-data", @id = "FrmUsuario" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="container">
                <h1>Cadastrar - Usuário</h1>
                <hr />
                <div class="col-md-12">
                    <div class="form-group">
                        @Html.LabelFor(model => model.appNome, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.appNome, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.appNome, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.appSenha, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.appSenha, new { htmlAttributes = new { @class = "form-control", Type = "password" } })
                        @Html.ValidationMessageFor(model => model.appSenha, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.appConfirmar, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.appConfirmar, new { htmlAttributes = new { @class = "form-control", Type = "password" } })
                        @Html.ValidationMessageFor(model => model.appConfirmar, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.appEmail, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.appEmail, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.appEmail, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.appCelular, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.appCelular, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.appCelular, "", new { @class = "text-danger" })
                        <br />
                        <input type="submit" value="Salvar" class="btn btn-default" />
                        <br />
                        <br />
                        @Html.ActionLink("Voltar ao Login", "LIndex", "Login")
                    </div>
                </div>
            </div>
        </div>
    }

    <div class="table">
        @{ Html.RenderPartial("Detalhes", @Model.SelecionarUsuarios());}
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
  
            @if(ViewBag.Mensagem!="")
            {
                <script>
                    alert(@ViewBag.Mensagem);
                </script>
            }
    }

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</body>